title: Shitong Zhu
url: "https://shitong.me"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

#tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Powered by Jekyll"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV [Sep 2020]"
   link: "pdfs/CV_Shitong_202009.pdf"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=xwOzrucAAAAJ&hl=en"
 - name: "Contact"
   link: "contact"
