title: Shitong Zhu
url: "https://shitong.me"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

#tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Powered by Jekyll"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV [Feb/2019]"
   link: "CV_Shitong_201902.pdf"
 - name: "Contact"
   link: "contact"
